name: OkiCore
main: com.okicraft.okicore.OkiCore
version: 0.8
author: Melonking, TheMIP3
description: Needed things for New OkiCraft
depend: [Vault,Nicky]

commands:
  hug:
    description: Hug someone!
  motd:
    description: Show the Motd!
  setnews:
    description: Set the Motd news!
  unsign:
    description: Unsign books!
  fix:
    description: Fix tools!
  okireload:
    description: OkiCore Reload!
  announce:
    description: Announce stuff!
    aliases: [anc]
  alert:
    description: Alert stuff!
  kickemall:
    description: Kick Everyone!
    aliases: [kea]
  giveeveryone:
    description: Give something to everyone!
  mollytalk:
    description: Talk as Molly!
    aliases: [mt]
  playertalk:
    description: Talk as someone!
    aliases: [pt]
  send:
    description: Send items to players!
  fly:
    description: Fly!
  seen:
    description: See when a player was last online!
  addpet:
    description: Adds a players pet perm!
  chat:
    description: Loy chat commands!
    aliases: [c,ch]
  pvp:
    description: Toggle pvp!
  prefixtoken:
    description: Spawn a prefix token!
    aliases: [pfxtoken]
  resurrect:
    description: Return players from the dead!
  emeralds:
    description: Get your emerald balance!
    aliases: [money,fe]